accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    url(r'^login/', auth_views.login, name='login'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'profile/', views.ProfileView.as_view(), name='profile')
]

characters/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^new/', views.CharacterCreateView.as_view(), name='create'),
    url(r'(?P<realm>[\w\-]+)/(?P<name>[\w\-]+)', views.CharacterDetailView.as_view(), name='detail'),
]

wowtrack/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^characters/', include('characters.urls', namespace='characters')),
    url(r'^$', views.HomeView.as_view(), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

characters/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ValidationError
import requests


class Character(models.Model):
    name = models.CharField(max_length=12)
    realm = models.CharField(max_length=30)
    user = models.ForeignKey(User)

    class Meta:
        unique_together = ('name', 'realm')

    def clean(self):
        request = requests.get(
            'https://us.api.battle.net/wow/character/%s/%s?locale=en_US&fields=items&apikey=%s' % (
                self.realm, self.name, 'x95frpjm3v3zdrnj3rbzr83e9b348hj9'
            ))

        if request.status_code != 200:
            raise ValidationError('Character not found')

    def save(self, *args, **kwargs):
        self.full_clean()
        return super(Character, self).save(*args, **kwargs)

    def __str__(self):
        return '%s - %s' % (self.name, self.realm)


class Snapshot(models.Model):
    character = models.ForeignKey(Character)
    item_level = models.IntegerField()

accounts/views.py
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.views import generic


class Logout(generic.RedirectView):
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class ProfileView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'accounts/profile.html'

characters/views.py
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.shortcuts import get_object_or_404
from . import models


class CharacterDetailView(LoginRequiredMixin, generic.DetailView):
    model = models.Character

    def get_object(self, queryset=None):
        return get_object_or_404(self.model, name__iexact=self.kwargs['name'], realm__iexact=self.kwargs['realm'])


class CharacterCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Character
    fields = ['name', 'realm']
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CharacterCreateView, self).form_valid(form)

wowtrack/views.py
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'index.html'

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}

{% block content %}
    {% for character in user.character_set.all %}
        <a class="character" href="/characters/{{ character.realm }}/{{ character.name }}">
            {{ character.name }}
        </a>
    {% endfor %}
{% endblock %}

characters/templates/characters/character_detail.html
{% extends 'layout.html' %}

{% block title %}{{ object.name }} - {{ object.realm }}{% endblock %}

{% block content %}
    {{ object.name }} - {{ object.realm }}
    <hr>
    {% for snapshot in object.snapshot_set.all %}
        {{ snapshot.item_level }}
        <br>
    {% endfor %}
{% endblock %}

characters/templates/characters/character_form.html
{% extends 'layout.html' %}

{% block content %}
    <form action="" method="post" autocomplete="off">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save"/>
    </form>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}{% endblock %}

{% block content %}
    <h2>Welcome</h2>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | WoWTrack</title>
</head>
<body>
    <header id="header">
        <nav>
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:logout' %}">Logout</a>
        </nav>
    </header>
    {% block content %}{% endblock %}
</body>
</html>